apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-container-service-poc-v6
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-container-service-poc-v6
    spec:
      containers:
      - name: azurecontainerservice
        image: acraramsam.azurecr.io/azurecontainerservice:v6
        ports:
        - containerPort: 80
        args: ["-it"]
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: dev
          value: "azure-container-service-poc-v6"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-container-service-poc-v6
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-container-service-poc-v6